#!/usr/bin/env python3
import ipaddress
from sys import argv

def get_range(cidr_notation):
    try:
        # Parse the CIDR notation to get the network object
        network = ipaddress.IPv4Network(cidr_notation, strict=False)
        #first_usable_ip = network.network_address + 1  # this is *usable*, but misses gateway/router in our implementation
        first_usable_ip = network.network_address 
        last_usable_ip = network.broadcast_address - 1

        return str(first_usable_ip), str(last_usable_ip)
    except ValueError as e:
        return str(e)
    

if __name__ == "__main__":
    try:
        cidr = argv[1]
    except:
        cidr = input("Enter the CIDR to get the range: ")

    ip_range = get_range(cidr)

    print(f"Start: {ip_range[0]}\n  End: {ip_range[1]}")
